In [1]:
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

2021-10-11 21:52:14.309581: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-11 21:52:14.309623: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

https://www.youtube.com/watch?v=1-NYPQw5THU&feature=youtu.be

In [2]:
import pandas as pd
import numpy as np
import datetime
from pandas_summary import DataFrameSummary

In [3]:
df = pd.read_feather('train_normalized_data.fth')
df_test = pd.read_feather('test_normalized_data.fth')

In [4]:
df_test

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,Year,Month,...,BeforePromo,level_0,index,SchoolHoliday_bw,StateHoliday_bool_bw,Promo_bw,index_fw,SchoolHoliday_fw,StateHoliday_bool_fw,Promo_fw
0,1,0,3,2015-09-17,1.0,1.273237,0,-0.466372,2,8,...,0,47,47,0,0,4,0,0,0,1
1,2,2,3,2015-09-17,1.0,1.273237,0,-0.466372,2,8,...,0,95,95,0,0,4,48,0,0,1
2,3,6,3,2015-09-17,1.0,1.273237,0,-0.466372,2,8,...,0,143,143,0,0,4,96,0,0,1
3,4,7,3,2015-09-17,1.0,1.273237,0,-0.466372,2,8,...,0,191,191,0,0,4,144,0,0,1
4,5,8,3,2015-09-17,1.0,1.273237,0,-0.466372,2,8,...,0,239,239,0,0,4,192,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,41084,1110,5,2015-08-01,1.0,-0.785400,0,-0.466372,2,7,...,-2,40848,40848,0,0,0,40895,5,0,5
41084,41085,1111,5,2015-08-01,1.0,-0.785400,0,-0.466372,2,7,...,-2,40896,40896,0,0,0,40943,5,0,5
41085,41086,1112,5,2015-08-01,1.0,-0.785400,0,-0.466372,2,7,...,-2,40944,40944,0,0,0,40991,5,0,5
41086,41087,1113,5,2015-08-01,1.0,-0.785400,0,-0.466372,2,7,...,-2,40992,40992,0,0,0,41039,5,0,5
41087,41088,1114,5,2015-08-01,1.0,-0.785400,0,2.144211,2,7,...,-2,41040,41040,1,0,0,41087,7,0,5

In [5]:
df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Year,...,BeforePromo,level_0,index,SchoolHoliday_bw,StateHoliday_bool_bw,Promo_bw,index_fw,SchoolHoliday_fw,StateHoliday_bool_fw,Promo_fw
0,0,4,2015-07-31,5263,555,1,1.273237,0,2.144211,2,...,0,941,941,5,0,5,0,1,0,1
1,1,4,2015-07-31,6064,625,1,1.273237,0,2.144211,2,...,0,1883,1883,5,0,5,942,1,0,1
2,2,4,2015-07-31,8314,821,1,1.273237,0,2.144211,2,...,0,2825,2825,5,0,5,1884,1,0,1
3,3,4,2015-07-31,13995,1498,1,1.273237,0,2.144211,2,...,0,3767,3767,5,0,5,2826,1,0,1
4,4,4,2015-07-31,4822,559,1,1.273237,0,2.144211,2,...,0,4709,4709,5,0,5,3768,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844333,681,1,2013-01-01,3375,566,1,-0.785400,1,2.144211,0,...,-6,620526,620526,1,1,0,621467,4,1,1
844334,732,1,2013-01-01,10765,2377,1,-0.785400,1,2.144211,0,...,-6,666728,666728,1,1,0,667669,4,1,1
844335,768,1,2013-01-01,5035,1248,1,-0.785400,1,2.144211,0,...,-6,699720,699720,1,1,0,700661,4,1,1
844336,947,1,2013-01-01,4491,1039,1,-0.785400,1,2.144211,0,...,-6,863186,863186,1,1,0,864127,4,2,1
844337,1096,1,2013-01-01,5961,1405,1,-0.785400,1,2.144211,0,...,-6,1000047,1000047,1,1,0,1000988,4,1,1

In [6]:
cat_vars = ['Store', 'DayOfWeek', 'Year', 'Month', 'Day', 'StateHoliday', 'CompetitionMonthsOpen', 'Promo2Weeks', 
            'StoreType', 'Assortment', 'PromoInterval', 'CompetitionOpenSinceYear', 'Promo2SinceYear', 'State', 
            'Week', 'Events', 'Promo_fw', 'Promo_bw', 'SchoolHoliday_fw', 'SchoolHoliday_bw']
# StateHoliday_fw, StateHoliday_bw
# cat_vars = ['Store', 'DayOfWeek', 'Year', 'Month', 'Day', 'State']

In [7]:
contin_vars = ['CompetitionDistance', 
   'Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC',
   'Max_Humidity', 'Mean_Humidity', 'Min_Humidity', 'Max_Wind_SpeedKm_h', 
   'Mean_Wind_SpeedKm_h', 'CloudCover', 'trend', 'trend_DE',
   'Promo', 'SchoolHoliday']
# AfterStateHoliday, BeforeStateHoliday
# contin_vars = []

In [8]:
from lightgbm import LGBMRegressor

In [9]:
y_out_columns = ['Sales']

In [10]:
# split_type = 'random'
# split_type = 'no_split'
split_type = 'last_week'

In [11]:
# Esta es para entrenar con todo
if split_type == 'no_split':
    df_train = df
elif split_type == 'last_week':
    # Esto divide en train y val
    df_train = df[df.Date < datetime.datetime(2015, 7, 1)]  
    df_val = df[df.Date >= datetime.datetime(2015, 7, 1)]
    print(f'Cantidad en val: {len(df_val)}, porcentaje: {len(df_train)/(len(df_train) + len(df_val))}')
elif split_type == 'random':
    # Splitting aleatorio
    np.random.seed(42)
    indexes = np.arange(len(df))
    np.random.shuffle(indexes)
    N = len(df)//5
    df_train = df[N:]
    df_val = df[:N]
    print(f'Cantidad en val: {len(df_val)}, porcentaje: {len(df_train)/(len(df_train) + len(df_val))}')

Cantidad en val: 30188, porcentaje: 0.9642465458145908

In [12]:
X_train = df_train[cat_vars + contin_vars]
if split_type != 'no_split':
    X_val = df_val[cat_vars + contin_vars]
X_test = df_test[cat_vars + contin_vars]

In [13]:
X_train

,Store,DayOfWeek,Year,Month,Day,StateHoliday,CompetitionMonthsOpen,Promo2Weeks,StoreType,Assortment,...,Max_Humidity,Mean_Humidity,Min_Humidity,Max_Wind_SpeedKm_h,Mean_Wind_SpeedKm_h,CloudCover,trend,trend_DE,Promo,SchoolHoliday
30188,0,1,2,5,29,0,24,25,2,0,...,-0.166351,-2.192275,-1.932272,0.036585,-0.317234,-2.314268,0.950700,0.807334,1.273237,-0.466372
30189,1,1,2,5,29,0,24,25,0,0,...,-0.684665,-1.283627,-1.117041,-1.081931,-0.656379,-0.493858,0.950700,0.807334,1.273237,-0.466372
30190,2,1,2,5,29,0,24,25,0,0,...,0.092806,-1.359348,-1.422752,-0.410822,-1.165096,-1.859165,1.479808,0.807334,1.273237,2.144211
30191,3,1,2,5,29,0,24,25,2,2,...,-1.462136,-1.737951,-1.422752,-0.187118,-0.317234,-0.493858,-0.019329,0.807334,1.273237,-0.466372
30192,4,1,2,5,29,0,2,25,0,0,...,-0.684665,-1.132186,-1.066089,-0.970080,-0.317234,-0.038755,-0.460252,0.807334,1.273237,-0.466372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844333,681,1,0,0,0,1,24,25,1,0,...,0.870277,0.306506,0.615325,0.372140,1.039345,0.416347,0.421593,-0.440285,-0.785400,2.144211
844334,732,1,0,0,0,1,24,25,1,1,...,0.092806,0.987991,0.768180,1.826211,2.395924,0.416347,-0.195698,-0.440285,-0.785400,2.144211
844335,768,1,0,0,0,1,24,5,1,1,...,0.092806,0.987991,0.768180,1.826211,2.395924,0.416347,-0.195698,-0.440285,-0.785400,2.144211
844336,947,1,0,0,0,1,24,25,1,1,...,-0.036773,0.457947,0.054854,0.036585,-0.995523,0.416347,-0.548436,-0.440285,-0.785400,2.144211
844337,1096,1,0,0,0,1,24,25,1,1,...,-0.166351,0.079344,0.462469,0.372140,1.208917,1.326552,-2.576680,-0.440285,-0.785400,2.144211

In [14]:
log_output = True
    
if log_output:
    # Escala logaritmica
    max_log_y = np.max(np.log(df[y_out_columns])).values
    y_train = np.log(df_train[y_out_columns].values)/max_log_y
    if split_type != 'no_split':
        y_val = np.log(df_val[y_out_columns].values)/max_log_y
else:
    # Normalización
    y_mean = df_train[y_out_columns].mean().values
    y_std = df_train[y_out_columns].std().values
    y_train = (df_train[y_out_columns].values - y_mean)/y_std
    if split_type != 'no_split':
        y_val = (df_val[y_out_columns].values - y_mean)/y_std

In [15]:
from sklearn.model_selection import cross_val_score
from hyperopt import hp, tpe
from hyperopt.fmin import fmin

In [16]:
def calculate_RMSE(X, y, log_output=True):
    y_preds = np.exp(model.predict(X, verbose=1)*max_log_y)
    return np.sqrt((((y - y_preds)/y)**2).sum()/len(y_preds))

In [17]:
X_train.shape

(814150, 34)

In [18]:
def objective(params):
    params = {
        # 'max_depth': int(params['max_depth']),
        # 'colsample_bytree': '{:.3f}'.format(params['colsample_bytree']),
        'learning_rate': '{:.4f}'.format(params['learning_rate'])
    }
    
    clf = LGBMRegressor(
        n_estimators=4000,
        min_child_samples= 5, max_depth= -1,
        **params
    )
    
    score = -cross_val_score(clf, X_train.values, y_train.reshape(-1)).mean()
    return score

In [19]:
space = {
    # 'max_depth': hp.quniform('max_depth', 1, 64, 4),
    # 'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 1.0),
    'learning_rate': hp.loguniform('learning_rate', -4, -2)
}

best = fmin(fn=objective,
            space=space,
            verbose=2,
            algo=tpe.suggest,
            max_evals=10)

100%|██████████| 10/10 [1:46:43<00:00, 640.39s/trial, best loss: -0.8851177778825801]

In [20]:
best

{'learning_rate': 0.1104653547927299}

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
parameters = {'learning_rate':[0.1, 0.05, 0.03], 'max_depth':[7, 3, 5]}
grid_search_res_1 = {'learning_rate': 0.1, 'min_child_samples': 5, 'max_depth': 7}
grid_search_res_2 = {'learning_rate': 0.05, 'max_depth': 7, 'min_child_samples': 20}

In [23]:
min_child_samples = 5
n_estimators = 4000
learning_rate = 0.06
model = LGBMRegressor(n_estimators=n_estimators, **grid_search_res_2)

In [24]:
clf = GridSearchCV(model, parameters, n_jobs=-1, verbose=1, cv=3)

In [25]:
clf

GridSearchCV(cv=3,
             estimator=LGBMRegressor(learning_rate=0.05, max_depth=7,
                                     n_estimators=4000),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.05, 0.03],
                         'max_depth': [7, 3, 5]},
             verbose=1)

In [26]:
fit_params={ "eval_metric" : 'l2', 
            'verbose': 100,
            'feature_name': 'auto', # that's actually the default
            'categorical_feature': cat_vars}
if split_type != 'no_split':
    fit_params["eval_set"] = [(X_val, y_val.reshape(-1))]
    fit_params["early_stopping_rounds"] = 100

In [27]:
clf.fit(X_train, y_train.reshape(-1), **fit_params)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.00028038
[200]	valid_0's l2: 0.000214745
[300]	valid_0's l2: 0.000192973
[400]	valid_0's l2: 0.000183771
[500]	valid_0's l2: 0.0001779
[600]	valid_0's l2: 0.000174155
[700]	valid_0's l2: 0.000171053
[800]	valid_0's l2: 0.000168744
[900]	valid_0's l2: 0.000167714
[1000]	valid_0's l2: 0.00016685
[1100]	valid_0's l2: 0.000166681
[1200]	valid_0's l2: 0.000166497
[1300]	valid_0's l2: 0.000165717
[1400]	valid_0's l2: 0.000165589
[1500]	valid_0's l2: 0.000165238
[1600]	valid_0's l2: 0.000164981
[1700]	valid_0's l2: 0.000165045
Early stopping, best iteration is:
[1615]	valid_0's l2: 0.000164954
Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.000455783
[200]	valid_0's l2: 0.000328839
[300]	valid_0's l2: 0.000281024
[400]	valid_0's l2: 0.000260895
[500]	valid_0's l2: 0.000244982
[600]	valid_0's l2: 0.000229991
[700]	valid_0's l2: 0.00021997
[800]	valid_0's l2: 0.00021196
[900]

/home/j3nnn1/anaconda3/envs/roosmanProject/lib/python3.9/site-packages/lightgbm/basic.py:1702: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
/home/j3nnn1/anaconda3/envs/roosmanProject/lib/python3.9/site-packages/lightgbm/basic.py:1705: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is ['Assortment', 'CompetitionMonthsOpen', 'CompetitionOpenSinceYear', 'Day', 'DayOfWeek', 'Events', 'Month', 'Promo2SinceYear', 'Promo2Weeks', 'PromoInterval', 'Promo_bw', 'Promo_fw', 'SchoolHoliday_bw', 'SchoolHoliday_fw', 'State', 'StateHoliday', 'Store', 'StoreType', 'Week', 'Year']
  _log_warning('categorical_feature in Dataset is overridden.\n'
/home/j3nnn1/anaconda3/envs/roosmanProject/lib/python3.9/site-packages/lightgbm/basic.py:1433: UserWarning: Overriding the parameters from Reference Dataset.
  _log_warning('Overriding the parameters from Reference Dataset.')
/home/j3nnn1/anaconda3/envs/roosmanProject/lib/python3.9/site-packages/lightgbm/basic.py:1245: UserWarning: categorical_column in param dict is overridden.
  _log_warning('{} in param dict is overridden.'.format(cat_alias))

Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.000233031
[200]	valid_0's l2: 0.00017438
[300]	valid_0's l2: 0.000146879
[400]	valid_0's l2: 0.000135527
[500]	valid_0's l2: 0.000128808
[600]	valid_0's l2: 0.000125175
[700]	valid_0's l2: 0.00012197
[800]	valid_0's l2: 0.000120694
[900]	valid_0's l2: 0.000119764
[1000]	valid_0's l2: 0.000119248
[1100]	valid_0's l2: 0.000118597
[1200]	valid_0's l2: 0.000117453
[1300]	valid_0's l2: 0.000117487
[1400]	valid_0's l2: 0.000117228
Early stopping, best iteration is:
[1375]	valid_0's l2: 0.000117051

GridSearchCV(cv=3,
             estimator=LGBMRegressor(learning_rate=0.05, max_depth=7,
                                     n_estimators=4000),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.05, 0.03],
                         'max_depth': [7, 3, 5]},
             verbose=1)

In [28]:
clf

GridSearchCV(cv=3,
             estimator=LGBMRegressor(learning_rate=0.05, max_depth=7,
                                     n_estimators=4000),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.05, 0.03],
                         'max_depth': [7, 3, 5]},
             verbose=1)

In [29]:
clf.best_params_
#{'learning_rate': 0.1, 'max_depth': 7}
#{'learning_rate': 0.1, 'max_depth': 5}

{'learning_rate': 0.1, 'max_depth': 5}

In [30]:
clf.best_score_
# 0.8758212241950689
# 0.8774792171111042

0.8774792171111042

In [31]:
model.fit(X_train, y_train.reshape(-1), **fit_params)

Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.000268587
[200]	valid_0's l2: 0.000196105
[300]	valid_0's l2: 0.000160331
[400]	valid_0's l2: 0.00014286
[500]	valid_0's l2: 0.000134206
[600]	valid_0's l2: 0.00012884
[700]	valid_0's l2: 0.000125877
[800]	valid_0's l2: 0.000123031
[900]	valid_0's l2: 0.000120997
[1000]	valid_0's l2: 0.000119671
[1100]	valid_0's l2: 0.000118332
[1200]	valid_0's l2: 0.000117624
[1300]	valid_0's l2: 0.000117113
[1400]	valid_0's l2: 0.000116714
[1500]	valid_0's l2: 0.000116175
[1600]	valid_0's l2: 0.000115487
[1700]	valid_0's l2: 0.000115034
[1800]	valid_0's l2: 0.000114898
[1900]	valid_0's l2: 0.000114606
[2000]	valid_0's l2: 0.000114558
Early stopping, best iteration is:
[1949]	valid_0's l2: 0.00011448

LGBMRegressor(learning_rate=0.05, max_depth=7, n_estimators=4000)

# Métrica

$$
\textrm{RMSE} = \sqrt{\frac{1}{n} \sum_{i=1}^{n} \left(\frac{\hat{y}_i - y_i}{y_i}\right)^2}
$$

In [32]:
model.score(X_val, y_val)

0.9198043472801825

In [33]:
if log_output:
    y_pred_train = np.exp(model.predict(X_train, verbose=1)*max_log_y)
    y_pred = np.exp(model.predict(X_val, verbose=1)*max_log_y)
    y_pred_test = np.exp(model.predict(X_test, verbose=1)*max_log_y)
else:
    y_pred_train = model.predict(X_train, verbose=1)*y_std + y_mean
    y_pred = model.predict(X_val, verbose=1)*y_std + y_mean
    y_pred_test = model.predict(X_test, verbose=1)*y_std + y_mean

In [34]:
# Train
np.sqrt((((df_train['Sales'].values - y_pred_train)/df_train['Sales'].values)**2).sum()/len(y_pred_train))

0.10367043050139678

In [35]:
# Validación
np.sqrt((((df_val['Sales'].values - y_pred)/df_val['Sales'].values)**2).sum()/len(y_pred))

0.11956440613746895

In [36]:
calculate_RMSE(X_train, df_train['Sales'].values)

0.10367043050139678

In [37]:
calculate_RMSE(X_val, df_val['Sales'].values)

0.11956440613746895

# Sumbit a la competición

In [38]:
sample_csv = pd.read_csv('dataset/rossmann/sample_submission.csv')
sample_csv['Sales'] = y_pred_test
sample_csv.head()

sample_csv.to_csv(f'submision_min_child_samples20_0.05_max_depth_7_lightgbm_{split_type}-{log_output}-{min_child_samples}-{n_estimators}-{learning_rate}.csv', index=False)